# Generated by Django 4.2.5 on 2023-09-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://as1.ftcdn.net/v2/jpg/04/52/57/94/1000_F_452579434_NfsqyndGpu1ahLMW9iDjpeiWaXGJhAMg.jpg', max_length=500),
        ),
    ]
